### ISSUE TITLE
Date alignment does not work

### ISSUE THREAD

**Issue by ryznzd** [Johnson070/MiBand-5-watchface-editor#15]
Date alignment does not seem to be working for me - selecting anything other than top left has no effect, even marker on the date does not change position accordingly. Please see the attached pic.
![date_bug](https://user-images.githubusercontent.com/77557314/115938881-60c04980-a49c-11eb-8e78-9b210965147a.JPG)

**Comment by Johnson070** [comment]
Your size is set 0, change value

**Comment by Johnson070** [comment]
Open test watchface from internet and see this work

**Comment by ryznzd** [comment]
Thanks, yeah, size was the problem.
