### ISSUE TITLE
Trojan virus detected

### ISSUE THREAD

**Issue by peminator** [Johnson070/MiBand-5-watchface-editor#16]
Trojan:Win32/Zpevdo.B!ctv
Detected by Microsoft Defender Antivirus

**Screenshots**
![trojanHuh](https://user-images.githubusercontent.com/1151036/116038518-d3caeb00-a669-11eb-9884-2dcf8a1adf82.png)

**Additional context**
Even as I wanted to see the source code, it still links to the exe, content unknown, so I cant try to inspect and rebuild the code my self.  I tried to look for a way to make own face for my Mi Band 6, this was one of few links, shame the trojan waring, now im very concerned, reading the MS site it may only be cause be some hidden encrypted content in the exe, maybe trying to change the compile settings may be helpfull? is there a source for it?

**Comment by Johnson070** [comment]
Hello, I wrote on the home page that it is not a virus. The program is currently protected from decompilation code. That is why the antivirus is trying to remove the program. If you are afraid or do not want to use the program, then uninstall it.

**Comment by Johnson070** [comment]
https://www.virustotal.com/gui/file/d57cefaeef35ec5ec56c213b73f9d885eb29bb77c9058b17410bac10daff93a5/detection

Check virustotal
