### ISSUE TITLE
I can't add progress bar

### ISSUE THREAD

**Issue by Cyber2525** [Johnson070/MiBand-5-watchface-editor#17]
**Describe the bug**
Wen I add the image they are ereased

<<<<<<< HEAD
**Attach bin or zip file**
zip
**Attach .bin file or zip**
zip
**Expected behavior**
>>>>>>> 7adb83f7cac56b016972c83dd2e6974ed4e18800

**Screenshots**

**Additional context**

**Comment by Johnson070** [comment]
Describe your problem in more detail, when adding which item you have a problem?
