### ISSUE TITLE
add pai progress

### ISSUE THREAD

**Issue by Cyber2525** [Johnson070/MiBand-5-watchface-editor#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Johnson070** [comment]
It is not possible to do this because mi band does not support this function

**Comment by hserranome** [comment]
Hi! I'be been using your tool, and it's been really useful. Thanks for your work!

About PAI progress:
For Mi Band 6 the default watch face has a PAI progress bar. It can't be done for custom watch faces?
