### ISSUE TITLE
Can't save as bin on version 1.0.1.4

### ISSUE THREAD

**Issue by lucscamps** [Johnson070/MiBand-5-watchface-editor#20]
After the update I'm unable to save as bin. I choose to save, but there is no bin file created.
If I use "save as" option, a .json is created instead. If I use the new option "save bin", only the .json is created, and I think it's because the .bin is being saved as .json and overwriting the original .json.

**Comment by Johnson070** [comment]
Thanks, I try to fix

**Comment by ChapayTv** [comment]
I have a similar problem, did you manage to solve something? When is the next update?

**Comment by Johnson070** [comment]
Release update 1.0.1.5
