### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by eduard-sukharev** [Johnson070/MiBand-5-watchface-editor#21]
Talk is cheap — if you say there're no viruses then show the source code. Why hiding it? It's a sidekick project, nothing official and i'm usre pure reverse-engineering.
Moreover, opening sources gives others opportunity to contribute.
Uploading only binaries to github is kinda dirty trick. 

You've made a great job creating this software, but be kind and also upload source.

**Comment by Johnson070** [comment]
You can talk about the source code as much as you want, I myself do not want to put it out yet, maybe it is a program that nobody needs, when I stop supporting it or pass it to someone else for support and will put the source code. WatchFace.exe also do not have the source code. I do not mind supporting the community, but as long as I do not want to see modifications

If you have any questions I can give you an opportunity to look at its source code

**Comment by Johnson070** [comment]
Problem in wininet.dll, antivirus warning

**Comment by Johnson070** [comment]
> Talk is cheap — if you say there're no viruses then show the source code. Why hiding it? It's a sidekick project, nothing official and i'm usre pure reverse-engineering.
> Moreover, opening sources gives others opportunity to contribute.
> Uploading only binaries to github is kinda dirty trick.
> 
> You've made a great job creating this software, but be kind and also upload source.

Source code in github released!

**Comment by elmissouri16** [comment]
@Johnson070  why do source code links on releases don't include source code they redirect you to exe release ? just wondering

**Comment by Johnson070** [comment]
> @Johnson070 why do source code links on releases don't include source code they redirect you to exe release ? just wondering

I write all source code on GitHub another repository
