### ISSUE TITLE
status icons seem to be inverted

### ISSUE THREAD

**Issue by aombk** [Johnson070/MiBand-5-watchface-editor#25]
in the editor the status icons for bluetooth and lock seem to be inverted meaning that when using the set watchface state i set bluetooth to on the off icon is displayed and the same happens for lock.

when uploading bin to mi band 6 the bluetooth icon seems to be working ok but the lock icon is inverted

thanks

**Comment by Johnson070** [comment]
You are sure, you will tests on mi band?

**Comment by Johnson070** [comment]
ok, thanks

**Comment by Johnson070** [comment]
Update 1.0.1.6
