### ISSUE TITLE
Wind Problems

### ISSUE THREAD

**Issue by lvfmc85** [Johnson070/MiBand-5-watchface-editor#3]
Hi, Thank you for this amazing tool.
I tried to create a wind speed info for my watchface, but I get an error when I try to create the watchface bin.
I generate the wind field using MiBand5WatchFaces from scratch, but I get this error on the log:

Debug|Reading config...
Fatal|********************************************************************************
Fatal|[ERROR]Error converting value "RightTop" to type 'WatchFace.Parser.Models.TextAlignment'. Path 'Weather.Wind.Text.Alignment', line 1, position 2772.

So I believe there's a bug in the coding for creating the wind field.

**Comment by Johnson070** [comment]
> Hi, Thank you for this amazing tool.
> I tried to create a wind speed info for my watchface, but I get an error when I try to create the watchface bin.
> I generate the wind field using MiBand5WatchFaces from scratch, but I get this error on the log:
> 
> Debug|Reading config...
> Fatal|********************************************************************************
> Fatal|[ERROR]Error converting value "RightTop" to type 'WatchFace.Parser.Models.TextAlignment'. Path 'Weather.Wind.Text.Alignment', line 1, position 2772.
> 
> So I believe there's a bug in the coding for creating the wind field.

Please attach this bin or zip file. I'll see today, and fix this

**Comment by Johnson070** [comment]
And next release with fixed bugs, tommorow.

**Comment by lvfmc85** [comment]
Thanks. Here is the zip with the images and JSON file.
I used the MiBandWFTool and, although I was able to create a bin file with wind speed, it only appears when the band is in English or Chinese language when the band is in any other language, the wind speed doesn't appear at all.
If you don't mind, could you also test if it is working for different languages?
Thank you very much!
[LVTest5.zip](https://github.com/Johnson070/MiBand-5-watchface-editor/files/6150926/LVTest5.zip)

**Comment by Johnson070** [comment]
> Thanks. Here is the zip with the images and JSON file.
> I used the MiBandWFTool and, although I was able to create a bin file with wind speed, it only appears when the band is in English or Chinese language when the band is in any other language, the wind speed doesn't appear at all.
> If you don't mind, could you also test if it is working for different languages?
> Thank you very much!
> [LVTest5.zip](https://github.com/Johnson070/MiBand-5-watchface-editor/files/6150926/LVTest5.zip)

Okay, I'll try to check in other languages and fix the bug

**Comment by Johnson070** [comment]
Thanks I figured out the problem should be TopRight and I have in my program RightTop, this is a critical error, I will correct in the update

**Comment by Johnson070** [comment]
The wind on the Mi band 5 does not appear in all languages, also check all of them because they are written wrong in some custom watchfaces

**Comment by lvfmc85** [comment]
Thank you! I tried several ways to write it but I could never do it work in other languages. Do you know which languages are compatible with wind speed and how to add it?
