### ISSUE TITLE
Can't open Mi Fit created watchfaces

### ISSUE THREAD

**Issue by Mineplayerminer** [Johnson070/MiBand-5-watchface-editor#31]
**Describe the bug**
I have created a watchface from my Mi Fit app and I wanted to edit it. I opened the .bin file and I ended up with a folder and inside it a text file describing the issue. Is it possible to open the watchfaces made in Mi Fit from a wallpaper?

**Attach .bin file or zip**
Attach [watchface]
[bf23c53cf016984412adc2cd23a9458e.zip](https://github.com/Johnson070/MiBand-5-watchface-editor/files/6604409/bf23c53cf016984412adc2cd23a9458e.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/82465758/120930222-a9e6f880-c6ec-11eb-8519-cd80188c6bb3.png)

**Additional context**
The Error "code":

`Trace|Reading image header...
Trace|Image header was read:
Trace|Width: 6, Height: 2, RowLength: 18
Trace|BPP: 24, PaletteColors: 0, Transaparency: False
Trace|The image doesn't use a palette.
Debug|Parsing parameters...
Trace|2 'Background'
Trace|2.1 'Image'
Trace|2.1.1 'X': 0
Trace|2.1.2 'Y': 0
Trace|2.1.3 'ImageIndex': 59
Fatal|System.ArgumentException: Parameter 6 isn't supported for Background
   at WatchFace.Parser.Utils.ParametersConverter.Parse[T](List`1 descriptor, String path)
   at MiCwU0e2dHM3cnc3H8.rC9cSqxd5BNoymSUH5.D5BJNoymS(Reader  )`

I also saw some errors about the color palette.

**Comment by DR34M3R-T** [comment]
It is said that the .bin file created by Mi Fit is encrypted, no matter the official watchface or the custom watchface.

**Comment by Johnson070** [comment]
> It is said that the .bin file created by Mi Fit is encrypted, no matter the official watchface or the custom watchface.

I dont know, i ask why does this happen

**Comment by Johnson070** [comment]
> It is said that the .bin file created by Mi Fit is encrypted, no matter the official watchface or the custom watchface.

MiBandWFTool not supported open mi fit created watchfaces(
