### ISSUE TITLE
GIF for band 5 watch faces not getting created.

### ISSUE THREAD

**Issue by aashitshah26** [Johnson070/MiBand-5-watchface-editor#32]
Gif is being created for mi band 6 watch faces but not for mi band 5 watch faces. How to create gif for mi band 5 watch faces ?

[aashit_packed.zip](https://github.com/Johnson070/MiBand-5-watchface-editor/files/6621077/aashit_packed.zip)

**Comment by Johnson070** [comment]
Click open watchface directory after compile bin, MiBandWFTool generating GIF preview not my program
