### ISSUE TITLE
SAVE FILE

### ISSUE THREAD

**Issue by proxpro200** [Johnson070/MiBand-5-watchface-editor#33]
can`t save the watchface.

ERROR
![Zrzut ekranu 2021-07-03 131234](https://user-images.githubusercontent.com/72352782/124352414-59d25780-dc00-11eb-85be-069365900750.png)
(can`t save a json too)

Thanks

**Comment by Johnson070** [comment]
This happens, because program saves images to path. He trying to overwrite files which using another files

**Comment by Johnson070** [comment]
Try close opened png files and save json
