### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by Kolerts89** [Johnson070/MiBand-5-watchface-editor#36]
![date](https://user-images.githubusercontent.com/87424163/125617647-6a9a1486-50b2-46a1-a3c8-72d786c65a5f.PNG)
![date2](https://user-images.githubusercontent.com/87424163/125617609-0de2cd07-ffab-46a3-929f-f0035a3fc736.PNG)

Hello! Please add the ability to configure the date separately (day, month, year) I also ask you to add the ability to configure the day, month, year in one line (example 14.07.2021)- at the moment 2021.07.14. Correct the separator (place it below in one line with the date)

Original Rus
Здравствуйте! Прошу добавить возможность настройки даты разделенно (день, месяц, год) Также прошу добавить возможность настройки день, месяц, год в одну строку (пример 14.07.2021)- в данный момент 2021.07.14. Поправить разделитель (разместить ниже в одну строку с датой)

**Comment by Johnson070** [comment]
Данный функционал невозможно добавить потому что это не поддерживается прошивкой
