### ISSUE TITLE
My watchface doesnt display activity numbers when applied to my watch

### ISSUE THREAD

**Issue by dijkmeneer** [Johnson070/MiBand-5-watchface-editor#39]
**Describe the bug**
In the editor the heartrate, kcal, pai, etc appear fine, but when synced the numbers are gone, the preview files also appear glitched
How it looks on the watch
![How it looks on the watch](https://user-images.githubusercontent.com/41268583/127775564-8cd4c0ec-ece6-40cc-99c1-d3f1ae9163d7.jpg)
How it looks in the editor and how its supposed to look
![How it looks in the editor and how its supposed to look](https://user-images.githubusercontent.com/41268583/127775566-65233597-1660-48ee-949f-c744bc7e3021.png)
How the preview file looks
![how the preview file looks](https://user-images.githubusercontent.com/41268583/127775567-5d5e6a0a-e59e-4b6e-bfcf-9a9ae3373d12.png)
 

**Attach .bin file or zip**
Attach watchface
[new_packed-529547-d2be7f10fe.zip](https://github.com/Johnson070/MiBand-5-watchface-editor/files/6912854/new_packed-529547-d2be7f10fe.zip)

**Comment by Johnson070** [comment]
Please check size of box in json, if size is 0 change to number > 1

**Comment by dijkmeneer** [comment]
None of the box sizes are 0 in the editor but i coudnt find it in the json file
[new_packed-529547-d2be7f10fe_packed-529547-daa07d1d7e.log](https://github.com/Johnson070/MiBand-5-watchface-editor/files/6925983/new_packed-529547-d2be7f10fe_packed-529547-daa07d1d7e.log)

**Comment by dijkmeneer** [comment]
I also tried a factory reset but it still does it on my watch.

**Comment by dijkmeneer** [comment]
I didnt add a decimal point to the distance number, this fixed it.
