### ISSUE TITLE
Is there any way to make progress bar behind digits?

### ISSUE THREAD

**Issue by 2eronia** [Johnson070/MiBand-5-watchface-editor#40]
I wanna design a watchface with a progress bar and activity digits at the same line.
But the progress bar is always being the upper layer of the digits.

Is there any way to get the progress bar behind?

**Comment by Johnson070** [comment]
Hello, you don't can. Sorry layers set in firmware

**Comment by 2eronia** [comment]
Sad : (

Thanks for your reply.
