### ISSUE TITLE
App crashes after import images for Today's Temperature Separate

### ISSUE THREAD

**Issue by lvfmc85** [Johnson070/MiBand-5-watchface-editor#5]
When I try to add the numeric images on Today Temperature, the app crashes.
This only happens on the separate option. The single line seems to be working.
Attached are the screenshots and below the complete error message I got.

![BUG0](https://user-images.githubusercontent.com/48862041/111543205-1a632680-8749-11eb-8b11-fa5bd380146a.JPG)
![BUG1](https://user-images.githubusercontent.com/48862041/111543212-1c2cea00-8749-11eb-851f-41018947d349.JPG)

#################################################################
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ‬⁬‬‌‪⁬⁫‎⁯‍⁭‫⁫‌‭‪⁪‌⁯​‬⁯‎‫‫‌‭⁭​⁬⁬‍⁪⁭‬⁬⁫‌‎⁯‮.⁯⁮‍‭‏⁫⁮‎‫‏‏⁬‫⁭‪‭⁭‎⁭‍‬‌⁭‌⁭⁪⁪‮‪⁫⁯⁪‪⁭‌⁬​‏⁪‮‮(Weather )
   at ‬⁬‬‌‪⁬⁫‎⁯‍⁭‫⁫‌‭‪⁪‌⁯​‬⁯‎‫‫‌‭⁭​⁬⁬‍⁪⁭‬⁬⁫‌‎⁯‮.⁯‏‮‏⁭⁪⁯⁯‭⁬⁬‍‪⁫⁭‏⁪‍‏​⁪‫⁮‎⁮‍​‭⁮⁬‍⁫⁭‪‌‎⁬‬‍‪‮()
   at nL$\\0(nOG\,vU9N'h4%UtK(Al$.⁭⁫‌⁬‫⁫‭‌‎⁫‭‮‌⁭‮‭⁫‌⁬‌‌‬⁪‬‬⁪‌‏⁯​‭‮‭⁪​‮⁮⁬⁭‏‮()
   at nL$\\0(nOG\,vU9N'h4%UtK(Al$.‭‬‪⁯⁬⁪‭‭​‎‍‬⁪‍⁪⁫⁫⁫‎‌‬‏‫‎‍‍⁯⁮‍⁫⁯‪‬‎‫‪‭⁫​⁮‮(Object , EventArgs )
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.ComboBox.set_Text(String value)
   at nL$\\0(nOG\,vU9N'h4%UtK(Al$.‎⁮⁪‭⁪⁮⁭‏⁯‭⁭‬‎‍‎‌‫⁯⁮⁬⁮‮‎‬‮⁭​‏⁭⁫‏⁮‭⁯⁭‫‎⁮‍⁫‮(Object , EventArgs )
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MiBand5WatchFaces
    Assembly Version: 1.0.0.8
    Win32 Version: 1.0.0.8
    CodeBase: file:///C:/Users/XXXXX/MiBand5WatchFaces.exe
----------------------------------------
DPXOxOcwDRSSSmDzuNIJEmzlkxZr
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.8
    CodeBase: file:///C:/Users/XXXXX/MiBand5WatchFaces.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
NzkhlIYYaUqtXRhkAfEVBVImjUNIA
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.8
    CodeBase: file:///C:/Users/XXXXX/MiBand5WatchFaces.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/XXXXX/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
#################################################################

**Comment by Johnson070** [comment]
Ok, I will see today, and fix in next update

**Comment by Johnson070** [comment]
I found bug, fix next release
