### ISSUE TITLE
Images in editor are bigger than they are

### ISSUE THREAD

**Issue by axmed2004** [Johnson070/MiBand-5-watchface-editor#59]
**Describe the bug**
All images in editor are looking bigger, but on watches is ok, so its difficult to edit face. Coords are correct. All images are png 96 dpi

![watchfaceeditor_screenshot](https://user-images.githubusercontent.com/6008055/147360290-7b071d1a-6d7e-4d4c-a083-d8a86789ea8e.jpg)
[simple_steps_alarm_packed.zip](https://github.com/Johnson070/MiBand-5-watchface-editor/files/7774638/simple_steps_alarm_packed.zip)

**Comment by Johnson070** [comment]
Change windows scale text to 100%

**Comment by axmed2004** [comment]
> Change windows scale text to 100%

many thanks. that solved problem
