### ISSUE TITLE
Select multiple images at once using shift

### ISSUE THREAD

**Issue by matheusunitt** [Johnson070/MiBand-5-watchface-editor#6]
Feature:
Select multiple images at once, so we could delete, activate or deactivate all at once.

**Comment by Johnson070** [comment]
Ok, I will try add this feature in next update, thanks)

**Comment by Johnson070** [comment]
I add possibility press CTRL and move mouse auto select items

**Comment by matheusunitt** [comment]
Thanks

**Comment by Johnson070** [comment]
> Feature:
> Select multiple images at once, so we could delete, activate or deactivate all at once.

i add this feature, press Left mouse click, remove left click + shift
