### ISSUE TITLE
Mi Band 6 has been released, I can’t wait to make a watch face

### ISSUE THREAD

**Issue by qgf718** [Johnson070/MiBand-5-watchface-editor#7]
Mi Band 6 has been released, I can’t wait to make a watch face

**Comment by Johnson070** [comment]
I mind add support mi band 6, how the documentation will appear I will go to do support

**Comment by Johnson070** [comment]
![image](https://user-images.githubusercontent.com/33296925/114285282-c0f7ca00-9a5e-11eb-99d3-aa8cf6aa0d2b.png)

Work in process

**Comment by qgf718** [comment]
Can the watch face editor of mi band 5 released by you be used for miband 6? Or the watch face editor shown in the screenshot is different from the watch face editor of miband 5?Can I take part in the test of the watch face editing tool of mi band 6 ?

**Comment by qgf718** [comment]
Can the watch face editor of mi band 5 released by you be used for miband 6? Or the watch face editor shown in the screenshot is different from the watch face editor of miband 5?Can I take part in the test of the watch face editing tool of mi band 6 ?

**Comment by Johnson070** [comment]
> Can the watch face editor of mi band 5 released by you be used for miband 6? Or the watch face editor shown in the screenshot is different from the watch face editor of miband 5?Can I take part in the test of the watch face editing tool of mi band 6 ?

I decided to combine for the 5 and 6 mi band.

I will ask permission from the developer who wrote the program to compile watchface

**Comment by qgf718** [comment]
I found that the watch face of mi band 5 can be installed on the mi band 6,And the compilation tool of Mi Band 5 can be used on Mi Band 6,The only disadvantage is that the size of the compiled bin file cannot be larger than 615kb.

**Comment by Johnson070** [comment]
even interesting how it looks

**Comment by qgf718** [comment]
Yes, if the generated bin file size limit can be cancelled, then the watch face for the Mi Band 6 can be successfully made.（Please ignore my bad English）

**Comment by qgf718** [comment]
Yes, if the generated bin file size limit can be cancelled, then the watch face for the Mi Band 6 can be successfully made.（Please ignore my bad English）
