### ISSUE TITLE
want to learn more

### ISSUE THREAD

**Issue by joelianruntu** [Johnson070/MiBand-5-watchface-editor#9]
hi, i had downloaded & tried it, that's good. Here I really want to know how the tool makes json & images become a .bin file. Would u like to opensource the tool.exe or teach me how it works? thx u very much!

**Comment by Johnson070** [comment]
Hello, I use another program for compiling. I asked the developer for permission to use in my product

Try to search information in google.

https://amazfitwatchfaces.com/forum/viewtopic.php?f=29&t=720
